### ISSUE TITLE
http://www.bogotobogo.com/MEAN-Stack/MEAN-Stack-MongoDB-ExpressJS-AngularJS-NodeJS-PollsApp-1.php  you can add this item more

### ISSUE THREAD

**Issue by donhuvy** [ericdouglas/MEAN-Learning#13]
part 1: http://www.bogotobogo.com/MEAN-Stack/MEAN-Stack-MongoDB-ExpressJS-AngularJS-NodeJS-PollsApp-1.php

you can add this item more

**Comment by donhuvy** [comment]
part 2: http://www.bogotobogo.com/MEAN-Stack/MEAN-Stack-MongoDB-ExpressJS-AngularJS-NodeJS-PollsApp-2.php

**Comment by ericdouglas** [comment]
@donhuvy thank you! :smile:
